-- SS_CACHED_PLANS 테이블에 검색 성능 향상을 위한 컬럼 추가
-- DURATION_WEEKS: 계획된 주수 (3개월 = 12주)
-- WEEKLY_FREQUENCY: 주간 빈도 (주 3회 = 3)

-- 1단계: 컬럼 추가
ALTER TABLE SS_CACHED_PLANS 
ADD COLUMN DURATION_WEEKS INT,
ADD COLUMN WEEKLY_FREQUENCY INT;

-- 2단계: 인덱스 추가 (검색 성능 향상)
CREATE INDEX IDX_DURATION_WEEKS ON SS_CACHED_PLANS(DURATION_WEEKS);
CREATE INDEX IDX_WEEKLY_FREQUENCY ON SS_CACHED_PLANS(WEEKLY_FREQUENCY);
CREATE INDEX IDX_DURATION_FREQUENCY ON SS_CACHED_PLANS(DURATION_WEEKS, WEEKLY_FREQUENCY);

-- 3단계: 기존 데이터 업데이트 (JSON에서 추출)
-- 나중에 LLM으로 실제 값 채워넣을 예정
UPDATE SS_CACHED_PLANS 
SET DURATION_WEEKS = JSON_EXTRACT(PLAN_DATA, '$.duration_weeks'),
    WEEKLY_FREQUENCY = JSON_EXTRACT(PLAN_DATA, '$.weekly_frequency')
WHERE JSON_EXTRACT(PLAN_DATA, '$.duration_weeks') IS NOT NULL
  AND JSON_EXTRACT(PLAN_DATA, '$.weekly_frequency') IS NOT NULL;

-- 완료: 이제 DURATION_WEEKS, WEEKLY_FREQUENCY로 빠른 검색 가능!
