-- SS_GOAL_TEMPLATES 테이블에 CACHED_PLAN_ID 컬럼 추가 및 외래키 설정

-- 1단계: CACHED_PLAN_ID 컬럼 추가
ALTER TABLE SS_GOAL_TEMPLATES 
ADD COLUMN CACHED_PLAN_ID VARCHAR(36) NULL;

-- 2단계: 외래키 제약조건 추가
ALTER TABLE SS_GOAL_TEMPLATES 
ADD CONSTRAINT FK_GOAL_TEMPLATES_CACHED_PLAN 
FOREIGN KEY (CACHED_PLAN_ID) 
REFERENCES SS_CACHED_PLANS(ID) 
ON DELETE SET NULL 
ON UPDATE CASCADE;

-- 3단계: 인덱스 추가 (성능 최적화)
CREATE INDEX IDX_GOAL_TEMPLATES_CACHED_PLAN_ID 
ON SS_GOAL_TEMPLATES(CACHED_PLAN_ID);

-- 완료: 이제 SS_GOAL_TEMPLATES와 SS_CACHED_PLANS가 연결됩니다!
